# arxivの学問領域の指定
subject: 'cat:astro-ph.GA'

# 検索キーワード
keywords:
        spiral: 3
        bar: 1
        thin disc: 1
        thin disk: 1
        thick disc: 1
        thick disk: 1
        formation: 1
        cepheid: 2
        warp: 2
        milky way: 2
        radial migration: 3
# 通知の閾値
score_threshold: 4
